import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import '@/styles/globals.scss';

const openSans = Open_Sans({
    variable: '--font-open-sans',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Fakebook',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${openSans.variable}`}>{children}</body>
        </html>
    );
}
